version: '3.9'
services:
  social-anti-club:
    build: ./
    command: ./main
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - .:/docker-entrypoint-initdb
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"