pg:
  host: db
  port: 5432
  db: social
  user: social
  pass: qwerty
  pool_size: 100

server:
  http_port: 8080
  grpc_port: 5000
  metrics_port: 8082

user_service:
  token_expiration: 1h
  token_secret: very-secret-shit