pg:
  host: db
  port: 5432
  db: social
  user: social
  pass: qwerty
  pool_size: 10

server:
  http1_port: 8080
  http2_port: 8081
  grpc_port: 5000

user_service:
  token_expiration: 1h
  token_secret: very-secret-shit