pg:
  host: 127.0.0.1
  port: 5436
  db: social
  user: social
  pass: qwerty
  pool_size: 10

server:
  http1_port: 80
  http2_port: 81
  grpc_port: 5000

user_service:
  token_expiration: 1h
  token_secret: very-secret-shit