pg:
  master:
    host: 127.0.0.1
    port: 6532
    db: social
    user: social
    pass: qwerty
    pool_size: 100
    max_conn_lifetime: 1m

  async:
    host: 127.0.0.1
    port: 7632
    db: social
    user: social
    pass: qwerty
    pool_size: 100
    max_conn_lifetime: 1m

  default_role: master

server:
  http_port: 8080
  grpc_port: 5000
  grpc_keep_alive: 120s
  metrics_port: 8082

user_service:
  token_expiration: 1h
  token_secret: very-secret-shit