global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prom'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'app'
    scrape_interval: 10s
    static_configs:
    - targets: ['app:8082']